ACK_ACCEPTANCE = 0b0001
ACK_START = 0b0010
ACK_PROGRESS = 0b0100
ACK_COMPLETION = 0b1000

PUS_SERVICE_REQUEST_VERIFICATION = 1

PUS_SUBSERVICE_REQUEST_ACK_SUCCESSFUL = 1
PUS_SUBSERVICE_REQUEST_START_SUCCESSFUL = 3
PUS_SUBSERVICE_REQUEST_SUCCESSFUL_PROGRESS = 5
PUS_SUBSERVICE_REQUEST_SUCCESSFUL_COMPLETION = 7

APID_DHU_TC = 1070
APID_DHU_HK = 1080
VALUE_PUS_VERSION = 2


